name: toffy_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - seaborn
  - scikit-learn
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pip:
    - natsort
    - watchdog
    - alpineer>=0.1.10
    - mibi-bin-tools==0.2.14
    - toffy==0.3.3
